version: '3'
services:
  dev-database:
    image: postgres:11.2
    environment:
      POSTGRES_USER: hackmd
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hackmd
  dev-hackmd:
    build:
      dockerfile: ./deployments/dev-Dockerfile
      context: ../
    environment:
      CMD_DB_URL: postgres://hackmd:password@dev-database/hackmd
    volumes:
      - ../:/hackmd
      - node_modules:/hackmd/node_modules
      - public_build:/hackmd/public/build
      - public_view_build:/hackmd/public/views/build
    ports:
      - 3000:3000
volumes:
  node_modules:
  public_build:
  public_view_build:
