name: Build Steps

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      platform_pair:
        required: true
        type: string
      registry_image:
        required: true
        type: string
      runtime:
        required: true
        type: string
      buildpack:
        required: true
        type: string
      runs_on:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.runs_on }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry_image }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deployments/Dockerfile
          platforms: ${{ inputs.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ inputs.registry_image }},push-by-digest=true,name-canonical=true,push=true
          build-args: |
            RUNTIME=${{ inputs.runtime }}
            BUILDPACK=${{ inputs.buildpack }}
      -
        name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
      -
        name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ inputs.platform_pair }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
